version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    working_dir: /go/src
    volumes:
      - .:/go
    command: >
      sh -c "
        while true; do sleep 1; done
      "
      
